language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry
dist: xenial
sudo: true

matrix:
  include:
    - python: 3.6
    - python: 3.7
before_install:
  - touch ~/.taskrc
  - mkdir -p ~/.config/just-start/
  - cp example_config.toml ~/.config/just-start/preferences.toml
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install pip -U
install:
  - pip install tox
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
  - bash <(curl -s https://codecov.io/bash)
