language: python
dist: xenial
sudo: true

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

env:
  global:
    - TOXENV=py
    - LATEST_PYTHON=3.7

jobs:
  include:
    - stage: test
      python: 3.6
    - python: $LATEST_PYTHON
    - stage: "post-test checks"
      name: typing
      env: TOXENV=typing
      python: $LATEST_PYTHON
    - name: style
      env: TOXENV=style
      python: $LATEST_PYTHON

before_install:
  - touch ~/.taskrc
  - mkdir -p ~/.config/just-start/
  - cp example_config.toml ~/.config/just-start/preferences.toml
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - pip install pip -U

install:
  - pip install tox
script:
  - tox
