language: python
cache: pip
python:
  - "3.7"
before_install:
  - touch ~/.taskrc
  - mkdir -p ~/.config/just-start/
  - cp example_config.toml ~/.config/just-start/preferences.toml
  - pip3 install poetry
install:
  - poetry install
script:
  - poetry run coverage run --source=just_start,just_start_urwid -m pytest
  - coverage report
after_success:
  - bash <(curl -s https://codecov.io/bash)
