language: python
cache: pip
dist: xenial
sudo: true

matrix:
  include: 
    - python: 3.7
before_install:
  - touch ~/.taskrc
  - mkdir -p ~/.config/just-start/
  - cp example_config.toml ~/.config/just-start/preferences.toml
  - pip install poetry
install:
  - pip install tox
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
  - bash <(curl -s https://codecov.io/bash)
