language: python
python:
  - "3.6"
os:
  - linux
  - osx
before_install:
  - touch ~/.taskrc
  - mkdir -p ~/.config/just-start/
  - cp example_config.toml ~/.config/just-start/preferences.toml
install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --dev .
script:
  - pytest --cov=.
after_success:
  - bash <(curl -s https://codecov.io/bash)
