language: python
python:
  - "3.6"
before_install:
  - touch ~/.taskrc
  - pwd
install:
  - pip install -q .[dev]
script:
  - pytest --cov=.
after_success:
  - bash <(curl -s https://codecov.io/bash)
