[general]
password = "my password"
blocked_sites = [
    "facebook.com", "messenger.com", "youtube.com"
]

[pomodoro]
pomodoro_length = 30
short_rest = 6
long_rest = 18
cycles_before_long_rest = 5

[clients.just_start]
error_fg = 'dark red'
error_bg = 'black'


[[locations]]
    name = "work"

    [locations.activation]
    start = "08:00"
    end = "12:00"
    days = []

    [locations.general]
    notifications = false

    [locations.pomodoro]
    pomodoro_length = 60
    short_rest = 12
    long_rest = 36
    cycles_before_long_rest = 5

[[locations]]
    name = "home"

    [locations.activation]
    start = "12:30"
    end = "18:30"
    days = []

    [locations.general]
    notifications = true

    [locations.pomodoro]
    pomodoro_length = 60
    short_rest = 12
    long_rest = 36
    cycles_before_long_rest = 5
